# checks that the shared library exports the functions in monero_c.symbols and nothing else
# usage: cmake -DLIBRARY=libmonero_c.so -DEXPECTED=monero_c.symbols [-DNM=nm] -P check_symbols.cmake
# On Linux it reads the dynamic symbols with nm -D and looks at the functions. On macOS, for a .dylib, it reads the external symbols
# with nm -gU, which have an underscore in front, and any other symbol there fails too. Set NM for a library of another architecture

if (NOT NM)
  set(NM nm)
endif()

if (LIBRARY MATCHES "\\.dylib$")
  set(macos TRUE)
  set(nm_args -gU)
else()
  set(macos FALSE)
  set(nm_args -D --defined-only)
endif()

execute_process(COMMAND "${NM}" ${nm_args} "${LIBRARY}" OUTPUT_VARIABLE nm_out RESULT_VARIABLE nm_rc)
if (NOT nm_rc EQUAL 0)
  message(FATAL_ERROR "${NM} failed on ${LIBRARY}")
endif()

string(REPLACE "\n" ";" lines "${nm_out}")
set(exported "")
set(foreign "")
foreach (line IN LISTS lines)
  if (macos)
    if (line MATCHES "^[0-9a-fA-F]* ([A-Za-z]) _?(.+)$")
      set(type "${CMAKE_MATCH_1}")
      set(name "${CMAKE_MATCH_2}")
      if (type STREQUAL "T" AND name MATCHES "^monero_[A-Za-z0-9_]+$")
        list(APPEND exported "${name}")
      else()
        list(APPEND foreign "${name}")
      endif()
    endif()
  elseif (line MATCHES " T ([A-Za-z0-9_]+)$")
    set(name "${CMAKE_MATCH_1}")
    if (name MATCHES "^monero_")
      list(APPEND exported "${name}")
    else()
      list(APPEND foreign "${name}")
    endif()
  endif()
endforeach()

file(STRINGS "${EXPECTED}" expected)
set(missing ${expected})
list(REMOVE_ITEM missing ${exported})
set(added ${exported})
list(REMOVE_ITEM added ${expected})

if (missing OR added OR foreign)
  if (missing)
    message(SEND_ERROR "missing from the library: ${missing}")
  endif()
  if (added)
    message(SEND_ERROR "not in ${EXPECTED}: ${added}")
  endif()
  if (foreign)
    list(LENGTH foreign count)
    list(SUBLIST foreign 0 5 first)
    message(SEND_ERROR "${count} symbols outside the C ABI are exported, e.g. ${first}")
  endif()
else()
  list(LENGTH exported count)
  message(STATUS "${count} functions exported, as in ${EXPECTED}")
endif()
